from enum import StrEnum


class ReasonType(StrEnum):
    ARTICLE16_1_OUT_OF_SCOPE_OR_NO_AUTHORITY = "ARTICLE16_1_OUT_OF_SCOPE_OR_NO_AUTHORITY"
    ARTICLE16_2_ALREADY_ACCEPTED_OR_PROCESSED = "ARTICLE16_2_ALREADY_ACCEPTED_OR_PROCESSED"
    ARTICLE16_3_NOT_CONSUMER_DISPUTE = "ARTICLE16_3_NOT_CONSUMER_DISPUTE"
    ARTICLE16_4_EXPIRED = "ARTICLE16_4_EXPIRED"
    ARTICLE16_5_MISSING_OR_FALSE_MATERIALS = "ARTICLE16_5_MISSING_OR_FALSE_MATERIALS"
    ARTICLE16_6_IMPERSONATION_OR_REFUSE_VERIFY = "ARTICLE16_6_IMPERSONATION_OR_REFUSE_VERIFY"
    ARTICLE16_7_OTHER_LEGAL_REASONS = "ARTICLE16_7_OTHER_LEGAL_REASONS"
    UNKNOWN = "UNKNOWN"


class DecisionSource(StrEnum):
    RULE = "RULE"
    MODEL = "MODEL"
    RAG_LLM = "RAG_LLM"
    HUMAN = "HUMAN"
    FALLBACK = "FALLBACK"


class AcceptSuggestion(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    REVIEW = "REVIEW"
